name: glz
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy<2
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - numba
  - ipython
  - ipykernel
  - jupyterlab
  - notebook
  - ipywidgets
  - pytest
